version: '3.8'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_php
    volumes: 
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on: 
      - db
  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: facturacion
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
volumes:
  db_data: